# Generated by Django 5.1.1 on 2024-10-05 13:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Anak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Murid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nis', models.CharField(max_length=20)),
                ('alamat', models.TextField()),
                ('tanggal_lahir', models.DateField()),
                ('nama_ayah', models.CharField(max_length=100)),
                ('email_ayah', models.EmailField(max_length=254)),
                ('no_tlp_ayah', models.CharField(max_length=15)),
                ('nama_ibu', models.CharField(max_length=100)),
                ('email_ibu', models.EmailField(max_length=254)),
                ('no_tlp_ibu', models.CharField(max_length=15)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Pegawai',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('nip', models.CharField(max_length=20)),
                ('tanggal_lahir', models.DateField()),
                ('alamat', models.TextField()),
                ('no_telp', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('pendidikan_terakhir', models.CharField(max_length=100)),
                ('nama_suami_istri', models.CharField(max_length=100)),
                ('anak', models.ManyToManyField(to='pengguna.anak')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RiwayatPekerjaan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_perusahaan', models.CharField(max_length=100)),
                ('posisi', models.CharField(max_length=100)),
                ('tahun_masa_kerja', models.CharField(max_length=50)),
                ('pegawai', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pengguna.pegawai')),
            ],
        ),
    ]
