# Generated by Django 5.1.1 on 2024-10-05 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pengguna', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pegawai',
            name='anak',
            field=models.ManyToManyField(related_name='pegawai', to='pengguna.anak'),
        ),
    ]
