# Generated by Django 5.1.1 on 2024-10-05 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pengguna', '0002_alter_pegawai_anak'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pegawai',
            name='anak',
            field=models.ManyToManyField(blank=True, null=True, related_name='pegawai', to='pengguna.anak'),
        ),
    ]
