from django.contrib import admin
from .models import RW, Acara, About, Organisasi, Struktur, Fasilitas, Tentang, rt1, rt2, rt3, rt4, rt5, rt6, rt7, rt8, rt9, rt10, rt11
admin.site.register(Organisasi)
admin.site.register(Struktur)
admin.site.register(Tentang)
admin.site.register(About)
admin.site.register(Fasilitas)
admin.site.register(Acara)
admin.site.register(RW)
admin.site.register(rt1)
admin.site.register(rt2)
admin.site.register(rt3)
admin.site.register(rt4)
admin.site.register(rt5)
admin.site.register(rt6)
admin.site.register(rt7)
admin.site.register(rt8)
admin.site.register(rt9)
admin.site.register(rt10)
admin.site.register(rt11)
