# Generated by Django 4.2.11 on 2025-01-18 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anggota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('nomor_telepon', models.CharField(max_length=15)),
            ],
            options={
                'verbose_name': 'Anggota',
                'verbose_name_plural': 'Anggota',
                'ordering': ['nama'],
            },
        ),
        migrations.CreateModel(
            name='Lomba',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_lomba', models.CharField(max_length=255)),
                ('deskripsi', models.TextField()),
            ],
            options={
                'verbose_name': 'Lomba',
                'verbose_name_plural': 'Lomba',
                'ordering': ['nama_lomba'],
            },
        ),
        migrations.CreateModel(
            name='Ketua',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('nomor_telepon', models.CharField(max_length=15)),
                ('anggota', models.ManyToManyField(blank=True, related_name='peserta_lombas', to='Karang_Taruna.anggota')),
                ('lomba', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ketua_lomba', to='Karang_Taruna.lomba')),
            ],
            options={
                'verbose_name': 'Ketua',
                'verbose_name_plural': 'Ketua',
                'ordering': ['nama'],
            },
        ),
    ]
