# Generated by Django 4.2.11 on 2025-01-18 14:55

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('title', models.CharField(blank=True, default=False, max_length=50, null=True)),
                ('text', tinymce.models.HTMLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Acara',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('slug', models.SlugField(null=True, unique=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('content', tinymce.models.HTMLField()),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
            options={
                'verbose_name_plural': 'Acara',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Anggota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Fasilitas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=20, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('slug', models.SlugField(null=True, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Fasilitas',
                'ordering': ['-name'],
            },
        ),
        migrations.CreateModel(
            name='KartunLomba',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
                ('image', models.ImageField(blank=True, default='', null=True, upload_to='images/')),
                ('description', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Organisasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('text', tinymce.models.HTMLField()),
                ('slug', models.SlugField(null=True, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Organisasi',
                'ordering': ['-title'],
            },
        ),
        migrations.CreateModel(
            name='rt1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about', models.ImageField(blank=True, default='', null=True, upload_to='images/')),
                ('text', tinymce.models.HTMLField(blank=True, null=True)),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
                ('judul', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('contentkanan', tinymce.models.HTMLField(blank=True, null=True, verbose_name='Content Kiri')),
                ('contentkiri', tinymce.models.HTMLField(blank=True, null=True, verbose_name='Content Kanan')),
                ('image', models.ImageField(blank=True, default='', null=True, upload_to='images/')),
            ],
            options={
                'verbose_name_plural': 'RT  1',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='rt10',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about', models.ImageField(blank=True, default='', null=True, upload_to='images/')),
                ('text', tinymce.models.HTMLField(blank=True, null=True)),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
                ('judul', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('contentkanan', tinymce.models.HTMLField(blank=True, null=True, verbose_name='Content Kiri')),
                ('contentkiri', tinymce.models.HTMLField(blank=True, null=True, verbose_name='Content Kanan')),
                ('image', models.ImageField(blank=True, default='', null=True, upload_to='images/')),
            ],
            options={
                'verbose_name_plural': 'RT 10',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='rt11',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about', models.ImageField(blank=True, default='', null=True, upload_to='images/')),
                ('text', tinymce.models.HTMLField(blank=True, null=True)),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
                ('judul', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('contentkanan', tinymce.models.HTMLField(blank=True, null=True, verbose_name='Content Kiri')),
                ('contentkiri', tinymce.models.HTMLField(blank=True, null=True, verbose_name='Content Kanan')),
                ('image', models.ImageField(blank=True, default='', null=True, upload_to='images/')),
            ],
            options={
                'verbose_name_plural': 'RT 11',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='rt2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about', models.ImageField(blank=True, default='', null=True, upload_to='images/')),
                ('text', tinymce.models.HTMLField(blank=True, null=True)),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
                ('judul', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('contentkanan', tinymce.models.HTMLField(blank=True, null=True, verbose_name='Content Kiri')),
                ('contentkiri', tinymce.models.HTMLField(blank=True, null=True, verbose_name='Content Kanan')),
                ('image', models.ImageField(blank=True, default='', null=True, upload_to='images/')),
            ],
            options={
                'verbose_name_plural': 'RT  2',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='rt3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about', models.ImageField(blank=True, default='', null=True, upload_to='images/')),
                ('text', tinymce.models.HTMLField(blank=True, null=True)),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
                ('judul', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('contentkanan', tinymce.models.HTMLField(blank=True, null=True, verbose_name='Content Kiri')),
                ('contentkiri', tinymce.models.HTMLField(blank=True, null=True, verbose_name='Content Kanan')),
                ('image', models.ImageField(blank=True, default='', null=True, upload_to='images/')),
            ],
            options={
                'verbose_name_plural': 'RT  3',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='rt4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about', models.ImageField(blank=True, default='', null=True, upload_to='images/')),
                ('text', tinymce.models.HTMLField(blank=True, null=True)),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
                ('judul', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('contentkanan', tinymce.models.HTMLField(blank=True, null=True, verbose_name='Content Kiri')),
                ('contentkiri', tinymce.models.HTMLField(blank=True, null=True, verbose_name='Content Kanan')),
                ('image', models.ImageField(blank=True, default='', null=True, upload_to='images/')),
            ],
            options={
                'verbose_name_plural': 'RT  4',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='rt5',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about', models.ImageField(blank=True, default='', null=True, upload_to='images/')),
                ('text', tinymce.models.HTMLField(blank=True, null=True)),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
                ('judul', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('contentkanan', tinymce.models.HTMLField(blank=True, null=True, verbose_name='Content Kiri')),
                ('contentkiri', tinymce.models.HTMLField(blank=True, null=True, verbose_name='Content Kanan')),
                ('image', models.ImageField(blank=True, default='', null=True, upload_to='images/')),
            ],
            options={
                'verbose_name_plural': 'RT  5',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='rt6',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about', models.ImageField(blank=True, default='', null=True, upload_to='images/')),
                ('text', tinymce.models.HTMLField(blank=True, null=True)),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
                ('judul', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('contentkanan', tinymce.models.HTMLField(blank=True, null=True, verbose_name='Content Kiri')),
                ('contentkiri', tinymce.models.HTMLField(blank=True, null=True, verbose_name='Content Kanan')),
                ('image', models.ImageField(blank=True, default='', null=True, upload_to='images/')),
            ],
            options={
                'verbose_name_plural': 'RT  6',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='rt7',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about', models.ImageField(blank=True, default='', null=True, upload_to='images/')),
                ('text', tinymce.models.HTMLField(blank=True, null=True)),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
                ('judul', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('contentkanan', tinymce.models.HTMLField(blank=True, null=True, verbose_name='Content Kiri')),
                ('contentkiri', tinymce.models.HTMLField(blank=True, null=True, verbose_name='Content Kanan')),
                ('image', models.ImageField(blank=True, default='', null=True, upload_to='images/')),
            ],
            options={
                'verbose_name_plural': 'RT  7',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='rt8',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about', models.ImageField(blank=True, default='', null=True, upload_to='images/')),
                ('text', tinymce.models.HTMLField(blank=True, null=True)),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
                ('judul', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('contentkanan', tinymce.models.HTMLField(blank=True, null=True, verbose_name='Content Kiri')),
                ('contentkiri', tinymce.models.HTMLField(blank=True, null=True, verbose_name='Content Kanan')),
                ('image', models.ImageField(blank=True, default='', null=True, upload_to='images/')),
            ],
            options={
                'verbose_name_plural': 'RT  8',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='rt9',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about', models.ImageField(blank=True, default='', null=True, upload_to='images/')),
                ('text', tinymce.models.HTMLField(blank=True, null=True)),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
                ('judul', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('contentkanan', tinymce.models.HTMLField(blank=True, null=True, verbose_name='Content Kiri')),
                ('contentkiri', tinymce.models.HTMLField(blank=True, null=True, verbose_name='Content Kanan')),
                ('image', models.ImageField(blank=True, default='', null=True, upload_to='images/')),
            ],
            options={
                'verbose_name_plural': 'RT  9',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='RW',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=12, verbose_name='Nama Database')),
                ('slide', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Carousel')),
            ],
            options={
                'verbose_name_plural': '  RW',
                'ordering': ['text'],
            },
        ),
        migrations.CreateModel(
            name='Struktur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
            options={
                'verbose_name_plural': '  Struktur Organisasi',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tentang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
                ('judul', models.CharField(blank=True, default='', max_length=50)),
                ('contentkanan', tinymce.models.HTMLField(blank=True, null=True, verbose_name='Content Kiri')),
                ('contentkiri', tinymce.models.HTMLField(blank=True, null=True, verbose_name='Content Kanan')),
            ],
            options={
                'verbose_name_plural': ' Tentang Kami',
            },
        ),
        migrations.CreateModel(
            name='PesertaLomba',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('nomor_hp', models.CharField(blank=True, max_length=15, null=True)),
                ('tanggal_daftar', models.DateTimeField(auto_now_add=True)),
                ('anggota', models.ManyToManyField(blank=True, related_name='peserta_lombas', to='Websitert.anggota')),
                ('kartun_lomba', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='peserta_lombas', to='Websitert.kartunlomba')),
            ],
        ),
        migrations.AddField(
            model_name='kartunlomba',
            name='tags',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kartun_lombas', to='Websitert.tag'),
        ),
    ]
