# Generated by Django 4.2.11 on 2025-01-18 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Websitert', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tag',
            new_name='Jenis_Lomba',
        ),
    ]
