# Generated by Django 4.2.11 on 2025-01-18 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Websitert', '0002_rename_tag_jenis_lomba'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kartunlomba',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='pesertalomba',
            name='anggota',
        ),
        migrations.RemoveField(
            model_name='pesertalomba',
            name='kartun_lomba',
        ),
        migrations.DeleteModel(
            name='Anggota',
        ),
        migrations.DeleteModel(
            name='Jenis_Lomba',
        ),
        migrations.DeleteModel(
            name='KartunLomba',
        ),
        migrations.DeleteModel(
            name='PesertaLomba',
        ),
    ]
