# Generated by Django 5.1.1 on 2024-10-07 18:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('kurikulum_merdeka', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tagihan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jumlah', models.DecimalField(decimal_places=2, max_digits=10)),
                ('keterangan', models.CharField(max_length=255)),
                ('tanggal_dibuat', models.DateField(auto_now_add=True)),
                ('siswa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kurikulum_merdeka.siswa')),
            ],
        ),
        migrations.CreateModel(
            name='Pembayaran',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jumlah_dibayar', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tanggal_bayar', models.DateField(auto_now_add=True)),
                ('tagihan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pembayaran.tagihan')),
            ],
        ),
    ]
